{% set name = "rhash" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/rhash/RHash/archive/v{{ version }}.tar.gz
  sha256: 98e0688acae29e68c298ffbcdbb0f838864105f9b2bd8857980664435b1f1f2e
  patches:
    # osx port patch, not accepted upstream
    # https://sourceforge.net/p/rhash/feature-requests/23/
    - librhash-osx.patch  # [osx]

build:
  number: 0
  skip: true  # [win or not py36]

requirements:
  build:
    - toolchain
    - python

test:
  commands:
    - test -f "$PREFIX/include/rhash.h"
    - test -f "$PREFIX/lib/librhash.a"  # [unix]
    - test -f "$PREFIX/lib/librhash.so.0"  # [linux]
    - test -f "$PREFIX/lib/librhash.0.dylib"  # [osx]
    - rhash --version

about:
  home: http://rhash.anz.ru/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Great utility for computing hash sums'
  description: |
    RHash is a console utility for computing and verifying hash sums of files. It supports CRC32, MD4, MD5, SHA1, SHA256, SHA512, SHA3, Tiger, TTH, Torrent BTIH, AICH, ED2K, GOST R 34.11-94, RIPEMD-160, HAS-160, EDON-R 256/512, WHIRLPOOL and SNEFRU hash sums.
  doc_url: http://rhash.anz.ru/manpage.php
  dev_url: https://github.com/rhash/RHash

extra:
  recipe-maintainers:
    - xantares
