{% set name = "rhash" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/rhash/RHash/archive/v{{ version }}.tar.gz
  sha256: 600d00f5f91ef04194d50903d3c79412099328c42f28ff43a0bdb777b00bec62

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]

test:
  commands:
    - test -f "$PREFIX/include/rhash.h"
    - test -f "$PREFIX/lib/librhash${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/librhash.so.0"  # [linux]
    - test -f "$PREFIX/lib/librhash.0.dylib"  # [osx]
    - rhash --version

about:
  home: http://rhash.anz.ru/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Great utility for computing hash sums
  description: |
    RHash is a console utility for computing and verifying hash sums of files. It supports CRC32, MD4, MD5, SHA1, SHA256, SHA512, SHA3, Tiger, TTH, Torrent BTIH, AICH, ED2K, GOST R 34.11-94, RIPEMD-160, HAS-160, EDON-R 256/512, WHIRLPOOL and SNEFRU hash sums.
  doc_url: http://rhash.anz.ru/manpage.php
  dev_url: https://github.com/rhash/RHash

extra:
  recipe-maintainers:
    - xantares
    - isuruf
