# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "eciDlI1fWwZB0C7jGwR6Ksa9FMdM7Tfa+s5bWZESodnB2DdnDgZKiMyO6y3c4HWHbxsHvxNFhBCVag9QoukU3kXaUUWFCRQCbNxfutf6RNp3G0YeNjVfMZ56kGhUdF98+A/P16cG1+P9DvpVMhq4LvNEEImS8+Cv7Xp8WlDORI38k9gM/Nr+KMkC1Bb58xUdsfe5rXYmjbcR43t6NznhmRBnuZk+EHrjVBHP5bRg1wQhrGzXNfW2XQkZgTVigMcbpXlw2bJPgMsB7Lzh0GWU5QZwblLPnxdIlILBBa+uXmIB7rYvSvFm5MqCRbaEM8/pYLsA38pq3xkOYNHsvTSKWSstVuzmuvloygSaDwiuFTpsPZ1+v8bBE4/3C31GsqoglZ0jcNgM6S0by7e3kesiiIXKdJ4XLTFHwh7zfM13CDO9gbXl/J4chjuSgcExPkR3Hx/0ZvgYKqEqJS4+Er+iDtowaPAJYwCqfRqAAZg+g1/e/phA5ZeTrTqOfn4LDju4CY2yh/F2wWBlfnmWq0KgxdvFLlHyoJnEvspePfVqq+sfKMFfkU1Rcd5Bi8ZUSTdKON4ZMr4L8yCk5yUY/FzrQaD6a0TItpcEtGpIZFTlpVbVVubhGN2Bp84qQR/eLcwcve8zW/nx5FtapVp+T+Ms5SdR1Mt62hmI3Wlv0XJ+3Kk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml